name: Release Package to GitHub

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: echo "//npm.pkg.github.com/:_authToken=${NPM_AUTH_TOKEN}" >> .npmrc
        env:
          NPM_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
      - run: npm ci
      - run: npm run build
      - run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
